// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-f-_k7NQXLe-KqqPUfGvyqcTpK_HiZ0',
    appId: '1:665507003859:web:07801c227f89901460c326',
    messagingSenderId: '665507003859',
    projectId: 'mytravaly-4ae5e',
    authDomain: 'mytravaly-4ae5e.firebaseapp.com',
    storageBucket: 'mytravaly-4ae5e.firebasestorage.app',
    measurementId: 'G-SS13B7E0YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQCg0TdZgAK42y5PojY9VhswZP7irzDOI',
    appId: '1:665507003859:android:0425b1a0ecabf4dd60c326',
    messagingSenderId: '665507003859',
    projectId: 'mytravaly-4ae5e',
    storageBucket: 'mytravaly-4ae5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0VILzih4NLPb9TwGeQh1PhpE_i7COm8',
    appId: '1:665507003859:ios:e57212d3d948c00660c326',
    messagingSenderId: '665507003859',
    projectId: 'mytravaly-4ae5e',
    storageBucket: 'mytravaly-4ae5e.firebasestorage.app',
    iosBundleId: 'com.example.myTravely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0VILzih4NLPb9TwGeQh1PhpE_i7COm8',
    appId: '1:665507003859:ios:e57212d3d948c00660c326',
    messagingSenderId: '665507003859',
    projectId: 'mytravaly-4ae5e',
    storageBucket: 'mytravaly-4ae5e.firebasestorage.app',
    iosBundleId: 'com.example.myTravely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2-f-_k7NQXLe-KqqPUfGvyqcTpK_HiZ0',
    appId: '1:665507003859:web:e6ff2fef5662e42460c326',
    messagingSenderId: '665507003859',
    projectId: 'mytravaly-4ae5e',
    authDomain: 'mytravaly-4ae5e.firebaseapp.com',
    storageBucket: 'mytravaly-4ae5e.firebasestorage.app',
    measurementId: 'G-VWRF1R6H4N',
  );
}
